services:
  server:
    image: gitea/gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    restart: always

    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${WEB_PORT}:3000
      - ${SSH_PORT}:22
    depends_on:
      - db
 
  db:
    image: postgres
    restart: always
    environment:
       - POSTGRES_USER=gitea
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=gitea

    volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
  gitea-data:
  postgres-data:
