services:
  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - ${NC_PORT}:80
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    volumes:
      - app:/var/www/html
    depends_on:
     - db
     - redis
  db:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data/    
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    environment:
      - REDIS_PORT=6379     
  onlyoffice:
    image: onlyoffice/documentserver
    restart: unless-stopped
    ports:
      - ${ONLYOFFICE_PORT}:80
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s      
    environment:
      - JWT_SECRET=${JWT_SECRET}    
  drawio:
    image: jgraph/drawio
    ports:
      - ${DRAWIO_PORT}:8080
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s       
volumes:
  app:
  db:      
