services:
  nextcloud-aio-apache:
    depends_on:
      nextcloud-aio-onlyoffice:
        condition: service_started
        required: false
      nextcloud-aio-notify-push:
        condition: service_started
        required: false
      nextcloud-aio-nextcloud:
        condition: service_started
        required: false
    image: ghcr.io/nextcloud-releases/aio-apache:latest
    user: "33"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    ports:
      - ${APACHE_IP_BINDING}:${APACHE_PORT}:${APACHE_PORT}/tcp
      - ${APACHE_IP_BINDING}:${APACHE_PORT}:${APACHE_PORT}/udp
    environment:
      - NC_DOMAIN
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - APACHE_HOST=nextcloud-aio-apache
      - APACHE_PORT
      - ONLYOFFICE_HOST=nextcloud-aio-onlyoffice
      - TZ=${TIMEZONE}
      - APACHE_MAX_SIZE
      - APACHE_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - NOTIFY_PUSH_HOST=nextcloud-aio-notify-push
      - HARP_HOST=nextcloud-aio-harp
    volumes:
      - nextcloud_aio_nextcloud:/var/www/html:ro
      - nextcloud_aio_apache:/mnt/data:rw
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /usr/local/apache2/logs
      - /tmp
      - /home/www-data
    cap_drop:
      - NET_RAW

  nextcloud-aio-database:
    image: ghcr.io/nextcloud-releases/aio-postgresql:latest
    user: "999"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    expose:
      - "5432"
    volumes:
      - nextcloud_aio_database:/var/lib/postgresql/data:rw
      - nextcloud_aio_database_dump:/mnt/data:rw
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - TZ=${TIMEZONE}
      - PGTZ=${TIMEZONE}
    stop_grace_period: 1800s
    restart: unless-stopped
    shm_size: 268435456
    read_only: true
    tmpfs:
      - /var/run/postgresql
    cap_drop:
      - NET_RAW

  nextcloud-aio-nextcloud:
    depends_on:
      nextcloud-aio-database:
        condition: service_started
        required: false
      nextcloud-aio-redis:
        condition: service_started
        required: false
    image: ghcr.io/nextcloud-releases/aio-nextcloud:latest
    init: true
    healthcheck:
      start_period: 30s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 5
    expose:
      - "9000"
      - "9001"
    volumes:
      - nextcloud_aio_nextcloud:/var/www/html:rw
      - ${NEXTCLOUD_DATADIR}:/mnt/ncdata:rw
      - ${NEXTCLOUD_MOUNT}:${NEXTCLOUD_MOUNT}:rw
      - ${NEXTCLOUD_TRUSTED_CACERTS_DIR}:/usr/local/share/ca-certificates:ro
    environment:
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - POSTGRES_HOST=nextcloud-aio-database
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=nextcloud-aio-redis
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - APACHE_HOST=nextcloud-aio-apache
      - APACHE_PORT
      - NC_DOMAIN
      - ADMIN_USER
      - ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/mnt/ncdata
      - OVERWRITEHOST=${NC_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - ONLYOFFICE_SECRET
      - NEXTCLOUD_MOUNT
      - ONLYOFFICE_ENABLED
      - ONLYOFFICE_HOST=nextcloud-aio-onlyoffice
      - UPDATE_NEXTCLOUD_APPS
      - TZ=${TIMEZONE}
      - PHP_UPLOAD_LIMIT=${NEXTCLOUD_UPLOAD_LIMIT}
      - PHP_MEMORY_LIMIT=${NEXTCLOUD_MEMORY_LIMIT}
      - PHP_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - TRUSTED_CACERTS_DIR=${NEXTCLOUD_TRUSTED_CACERTS_DIR}
      - STARTUP_APPS=${NEXTCLOUD_STARTUP_APPS}
      - ADDITIONAL_APKS=${NEXTCLOUD_ADDITIONAL_APKS}
      - ADDITIONAL_PHP_EXTENSIONS=${NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS}
      - INSTALL_LATEST_MAJOR
      - REMOVE_DISABLED_APPS
      - NC_maintenance_window_start=1
      - NC_default_phone_region=${PHONE_REGION}
      - NC_skeletondirectory=
    stop_grace_period: 600s
    restart: unless-stopped
    cap_drop:
      - NET_RAW

  nextcloud-aio-init:
    image: ghcr.io/nextcloud-releases/aio-nextcloud:latest
    restart: no       
    volumes_from:
      - nextcloud-aio-nextcloud:rw  
    init: true
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        php occ app:install sociallogin --allow-unstable --force
        php occ app:disable support
        php occ app:disable firstrunwizard
        php occ app:disable survey_client 
        php occ app:disable updatenotification
        php occ app:enable nextcloud-aio
        php occ app:remove nextcloud-aio
        php occ config:app:set theming backgroundMime --value="backgroundColor"        
        php occ config:system:set --type=boolean knowledgebaseenabled --value=false
        php occ db:add-missing-indices
        php occ maintenance:repair --include-expensive
        php occ config:system:set enable_previews --type=boolean --value=false 
        php occ config:app:set --value "false" onlyoffice customizationFeedback
        php occ config:app:set --value "false" onlyoffice customizationHelp
        php occ config:app:set --value "false" onlyoffice preview
        php occ config:app:set --value "false" onlyoffice versionHistory
        php occ config:app:set --value "false" onlyoffice customization_plugins 
        php occ config:app:set --value "{\"doc\":\"true\",\"docm\":\"true\",\"docx\":\"true\",\"dot\":\"true\",\"dotm\":\"true\",\"dotx\":\"true\",\"epub\":\"true\",\"fb2\":\"true\",\"fodt\":\"true\",\"htm\":\"true\",\"html\":\"true\",\"hwp\":\"true\",\"hwpx\":\"true\",\"md\":\"false\",\"mht\":\"true\",\"mhtml\":\"true\",\"odt\":\"true\",\"ott\":\"true\",\"pages\":\"true\",\"rtf\":\"true\",\"stw\":\"true\",\"sxw\":\"true\",\"txt\":\"false\",\"wps\":\"true\",\"xml\":\"false\",\"csv\":\"true\",\"fods\":\"true\",\"numbers\":\"true\",\"ods\":\"true\",\"ots\":\"true\",\"sxc\":\"true\",\"xls\":\"true\",\"xlsb\":\"true\",\"xlsm\":\"true\",\"xlsx\":\"true\",\"xlt\":\"true\",\"xltm\":\"true\",\"xltx\":\"true\",\"fodp\":\"true\",\"key\":\"true\",\"odg\":\"true\",\"odp\":\"true\",\"otp\":\"true\",\"pot\":\"true\",\"potm\":\"true\",\"potx\":\"true\",\"pps\":\"true\",\"ppsm\":\"true\",\"ppsx\":\"true\",\"ppt\":\"true\",\"pptm\":\"true\",\"pptx\":\"true\",\"sxi\":\"true\",\"djvu\":\"true\",\"docxf\":\"true\",\"oform\":\"true\",\"oxps\":\"true\",\"pdf\":\"true\",\"xps\":\"true\",\"vsdx\":\"true\",\"vsdm\":\"true\",\"vssm\":\"true\",\"vssx\":\"true\",\"vstm\":\"true\",\"vstx\":\"true\"}" onlyoffice defFormats
        php occ config:app:set --value "{\"epub\":\"true\",\"fb2\":\"true\",\"html\":\"true\",\"odt\":\"true\",\"ott\":\"true\",\"rtf\":\"true\",\"txt\":\"false\",\"csv\":\"true\",\"ods\":\"true\",\"ots\":\"true\",\"odp\":\"true\",\"otp\":\"true\"}" onlyoffice editFormats  
    depends_on:
      nextcloud-aio-nextcloud:
        condition: service_healthy      

  nextcloud-aio-notify-push:
    image: ghcr.io/nextcloud-releases/aio-notify-push:latest
    user: "33"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    expose:
      - "7867"
    volumes:
      - nextcloud_aio_nextcloud:/var/www/html:ro
    environment:
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - TZ=${TIMEZONE}
    restart: unless-stopped
    read_only: true
    cap_drop:
      - NET_RAW

  nextcloud-aio-redis:
    image: ghcr.io/nextcloud-releases/aio-redis:latest
    user: "999"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    expose:
      - "6379"
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - nextcloud_aio_redis:/data:rw
    restart: unless-stopped
    read_only: true
    cap_drop:
      - NET_RAW

  nextcloud-aio-onlyoffice:
    image: ghcr.io/thomisus/onlyoffice-documentserver-unlimited:latest
    init: true
    healthcheck:
      start_period: 60s
      test: curl --fail http://localhost:80/ || exit 1
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 9
    expose:
      - "80"
    environment:
      - TZ=${TIMEZONE}
      - JWT_ENABLED=true
      - JWT_HEADER=AuthorizationJwt
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    volumes:
      - nextcloud_aio_onlyoffice:/var/lib/onlyoffice:rw
    restart: unless-stopped
    cap_drop:
      - NET_RAW

volumes:
  nextcloud_aio_apache:
    name: nextcloud_aio_apache
  nextcloud_aio_database:
    name: nextcloud_aio_database
  nextcloud_aio_database_dump:
    name: nextcloud_aio_database_dump
  nextcloud_aio_nextcloud:
    name: nextcloud_aio_nextcloud
  nextcloud_aio_onlyoffice:
    name: nextcloud_aio_onlyoffice
  nextcloud_aio_redis:
    name: nextcloud_aio_redis
  nextcloud_aio_nextcloud_data:
    name: nextcloud_aio_nextcloud_data

networks:
  default:
    driver: bridge
