services:

  imaginary:
    image: h2non/imaginary
    restart: always
    command: -cors -enable-url-source
    cap_add:
      - SYS_NICE

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    image: nextcloud
    restart: always
    ports:
      - ${NC_PORT}:80
    links:
      - db
      - redis
    volumes:
      - app:/var/www/html
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379

    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: always

volumes:
  app:
  db:      
